# my_file= open("file4.txt","w+")
my_file=open("file4.txt","a+")
a=my_file.read()
# print(a)
my_file.write("\nHi\nso i'm archana aarya here \nand she is doing engeneering in navgurukul")
print(my_file)
my_file.close()